services:
  bluetooth-connector:
    image: pinkynrg/bluetooth-speaker-reconnector:latest
    container_name: bluetooth-connector
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /run/dbus:/run/dbus
    devices:
      - /dev/snd:/dev/snd
    environment:
      - BT_MAC=XX:XX:XX:XX:XX:XX
      - BT_CHECK_INTERVAL=30
      - BT_TIMEOUT=15
    restart: always