services:
  bluetooth-connector:
    build: .
    container_name: bluetooth-connector
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /run/dbus:/run/dbus
    devices:
      - /dev/snd:/dev/snd
    environment:
      - BT_MAC=60:AB:D2:08:0C:32
      - BT_CHECK_INTERVAL=30
      - BT_TIMEOUT=15
    restart: always
