services:
  bluetooth-receiver:
    image: pinkynrg/bluetooth-receiver:latest
    container_name: bluetooth-receiver
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /run/systemd:/run/systemd
      - /tmp:/tmp
    devices:
      - /dev/snd
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - DEVICE_NAME=Snapcast Receiver
    restart: always
