services:
  snapserver:
    image: pinkynrg/snapserver:latest
    container_name: snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    environment:
      - DEVICE_NAME=Snapcast
    volumes:
      - /mnt/data/snapserver/cache:/data # this is needed to keep the Spotify cached credentials 
      - /mnt/data/snapserver/server.json:/root/.config/snapserver/server.json # these are the editable configurations from the ui
      - /mnt/data/snapserver/snapserver.conf:/etc/snapserver.conf # these are the startup configurations for snapserver
      - /tmp:/tmp # needed to access the Bluetooth FIFO
    restart: always
