services:
  snapclient:
    image: pinkynrg/snapclient:latest
    container_name: snapclient
    hostname: XXX-speaker
    network_mode: host
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
    environment:
      - TZ=Europe/Rome
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - XDG_RUNTIME_DIR=/run/user/1000
    restart: always
    command: ["snapclient", "-h", "snapcast.francescomeli.com", "-s", "pulse", "--hostID", "XXX-speaker"]